### ISSUE TITLE
注册用户头像接入 https://gravatar.com/

### ISSUE THREAD

**Issue by lsanotes** [Kotlin-lang-CN/Kotlin-CN#11]
就像github 一样，根据邮箱从 gravatar 网站上获取用户头像

**Comment by chpengzh** [comment]
感谢反馈，一开始我们有这个打算，但是经过简单调研发现 gravatar 默认头像的普及率并不高。后续会考虑将这个功能补齐。

**Comment by lsanotes** [comment]
coding.net  和 github.com 之类的网站都有在用，而且这些网站的用户和本站的用户应该是一类吧？

而且注册完的默认头像太丑了....

**Comment by chpengzh** [comment]
当前版本支持使用默认的gravatar.com头像，从github授权登录的用户能默认使用github账号头像
