### ISSUE TITLE
顶部 Logo 文字没有对齐

### ISSUE THREAD

**Issue by DemoJameson** [Kotlin-lang-CN/Kotlin-CN#12]
![image](https://user-images.githubusercontent.com/181192/27283648-db259e1e-5527-11e7-8030-766937256979.png)
如图所示，既不是底部对齐也不是居中对齐

**Comment by chpengzh** [comment]
收到，谢谢反馈，我们会立即处理

**Comment by wuyisheng** [comment]
谢谢反馈，已处理
