### ISSUE TITLE
GitHub 登录依然不可用

### ISSUE THREAD

**Issue by DemoJameson** [Kotlin-lang-CN/Kotlin-CN#15]
授权后弹出“获取第三方登录信息”的加载对话框，然后就刷新回首页了，依然是未登录状态

**Comment by chpengzh** [comment]
请问下使用的浏览器是什么

**Comment by DemoJameson** [comment]
Win 10 Chrome 版本 59.0.3071.86（正式版本）（64 位）

**Comment by chpengzh** [comment]
是否有弹出图示的完善用户信息的输入框

![image](https://user-images.githubusercontent.com/7821898/27508886-4fd8887c-5922-11e7-844e-9205d874a070.png)

**Comment by DemoJameson** [comment]
没有，转啊转就回到首页了
![image](https://user-images.githubusercontent.com/181192/27508896-9339ef5c-5922-11e7-9220-cf7d9a52a964.png)
![image](https://user-images.githubusercontent.com/181192/27508905-aec00888-5922-11e7-9b93-ea50de7b9d26.png)

**Comment by chpengzh** [comment]
扒了下日志，问题找到了，我讨厌kotlin反序列化的空值检测~

```
2017-06-24 21:18:19:519 E/Response com.fasterxml.jackson.databind.JsonMappingException: Parameter specified as non-null is null: method tech.kotlin.service.Githubs$GithubUserResp.setCompany, parameter <set-?>
```

**Comment by DemoJameson** [comment]
233，还是 Gson 暴力，不管怎么样都能成功

**Comment by chpengzh** [comment]
一样的，反序列化库再给一个field填值的时候如果没有指定@JvmField一定会去调用set方法，如果是null的话也会报错。

```kotlin
class Sample { var prop: String = "" }
```

在反序列化赋值

```json
{ "prop": null}
```
的时候无论是`gson`还是别的库都会报错,

如果定义是

```kotlin
class Sample { @JvmField var prop: String = "" }
```

的话那么赋值的时候都不会报错，而在使用`sample.prop`的时候会是`null`(明明申明的是notnull)，mdzz

**Comment by chpengzh** [comment]
再试试

**Comment by DemoJameson** [comment]
问题解决

**Comment by chpengzh** [comment]
可以继续在issue里提期望实现的功能
