### ISSUE TITLE
 参与项目

### ISSUE THREAD

**Issue by wilsonandusa** [Kotlin-lang-CN/Kotlin-CN#19]
hello 我想参与到kotlin china开发维护中 之前加了QQ讨论群但感觉人太多了聊的也比较杂 请问有没有小一点规模的开发群可以加入 比如微信群。

**Comment by chpengzh** [comment]
qq已邀请

**Comment by wilsonandusa** [comment]
我么？没有收到诶 （qq: 781850685）
