### ISSUE TITLE
友情链接申请

### ISSUE THREAD

**Issue by maoyutofu** [Kotlin-lang-CN/Kotlin-CN#29]
你好，Kotlin China站长！方便加个友情链接吗？

Java 中文社区 https://www.javafm.com/

---------------------------

透明背景logo
`http://7xk8kk.com1.z0.glb.clouddn.com/logo.png`

白底logo
`http://7xk8kk.com1.z0.glb.clouddn.com/logo-white.png`

**Comment by chpengzh** [comment]
侧边栏已添加友站链接
