### ISSUE TITLE
关于类的扩展

### ISSUE THREAD

**Issue by suchuyang** [Kotlin-lang-CN/Kotlin-CN#30]
类的扩展，可以让我们把类的不同类型的实现放在不同的文件中，这是一个很好的设定。

但是在使用过程中，我给类写扩展的时候，扩展的函数是top level 函数，这样就导致我无法在类前面使用open等字符，也不能扩展companion object，所以我无法把同一类型的功能完全放到扩展文件中。

比方说，我在扩展中编写了一个事件分发的函数：
```kotlin
fun UIView.dispatchTouchesEvent(touches:MutableList<UITouch>, withEvent: MotionEvent){
 touchesBegan(touches, withEvent)
}
```

这其中会调用子类重写的事件函数:touchesBegan,所以这个touchesBegan应该是open的，但是这种情况下，touchesBegan无法写入扩展，而必须写入主类中。

**Comment by chpengzh** [comment]
不好意思，我没有理解这个issue想要表达的意思

**Comment by ice1000** [comment]
![](https://raw.githubusercontent.com/ice1000/dialogs/master/raw/ice1000_0x01.jpg) 要使用 polymorphism 就不要使用 extension

**Comment by ice1000** [comment]
![](https://raw.githubusercontent.com/ice1000/dialogs/master/raw/ice1000_0x01.jpg) 这和这个网站有什么关系？请不要把issue区当成灌水区谢谢（
