### ISSUE TITLE
Github登录不成功

### ISSUE THREAD

**Issue by pye52** [Kotlin-lang-CN/Kotlin-CN#9]
点击"GitHub登录"，授权完毕跳转回主页的时候并没显示登录成功(页面右上角依旧是"注册" "登录" "GitHub登录"三个按钮
此时再点击"GitHub登录"会刷新2次页面

**Comment by chpengzh** [comment]
## 最新版本改善了github账号登录体验

### 1. 点击github登录后会进入加载态如下

<img width="1014" alt="default" src="https://user-images.githubusercontent.com/7821898/27286740-d20cc8a0-5533-11e7-9b14-cefb0665cab9.png">

### 2. 首次使用github账号登录的用户需要完善基本账号信息

<img width="849" alt="default" src="https://user-images.githubusercontent.com/7821898/27286821-161821ac-5534-11e7-8948-ced7ef9bb67c.png">

### 3. 或者绑定已有账号

<img width="881" alt="default" src="https://user-images.githubusercontent.com/7821898/27286843-2758f400-5534-11e7-80b5-224880b4bcc3.png">

**Comment by chpengzh** [comment]
在补充完首次登录信息之后，就能正常的使用github账号登录。
